### ISSUE TITLE
How to auto increment ID

### ISSUE THREAD

**Issue by murtll** [jillesvangurp/es-kotlin-wrapper-client#32]
Hello!
How can I add my object to ES with auto incremented ID? I know that I can do this via http post request, but I can`t find how to do  this via your client.

**Comment by jillesvangurp** [comment]
Autoincrementing is not a feature in Elasticsearch as far as I know. It can auto-generate a content hash when you create an object. The `IndexRepository` does not currently support that behavior. But it's something I could add.

If you need this, you can just use index client that comes with Elasticsearch directly. I will probably add this feature though; thanks for reporting this. I've just added this issue to the 1.0 milestone.

This would need to be fixed in the index repository (and the async one) as well as in the bulk session. Probably a good strategy would be to make the id parameter nullable and let it default to null (breaks compatibility because we would have to change parameter order).
